version: '3.8'

volumes:
  db-data:

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: ./front/
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9000:9000
    networks:
      - app-network

  server:
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/java_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_DB: java_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
